# Dependencies
highlighter:      rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Maëlle
tagline:          'Not a fish'
description:      ''
url:              http://maelle.github.io

author:
  name:           'Maëlle Salmon'
  url:            https://twitter.com/masalmon

paginate:         5

excerpt_separator: <!--more-->

gems:
  - jekyll-paginate
  - kramdown 
  - jekyll-gist
  - font-awesome-less
  - jekyll-feed

github:
  repo:           https://github.com/maelle

twitter_username:     ma_salmon
github_username:      maelle
linkedin_username:    
google_plus_username: 
facebook_username:    
dribbble_username:
researchgate_username: Maelle_Salmon
mailto: maelle.salmon@yahoo.se
